name: Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          # We can't use "bundler-cache" because we want to install MSYS2
          # packages such as mingw-w64-ucrt-x86_64-pkg-config
          # automatically by installing gems such as rcairo.
          # bundler-cache: true
      - name: Install dependencies
        run: |
          bundle install
      - name: Build
        run: |
          bundle exec ruby -rdevkit -S rake build
      - name: "Test: glib2"
        run: |
          cd glib2
          bundle exec ruby -rdevkit test/run-test.rb
      - name: "Test: gobject-introspection"
        run: |
          cd gobject-introspection
          bundle exec ruby -rdevkit test/run-test.rb

  gem:
    name: Gem
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      PACKAGES: "glib2,gobject-introspection"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Build
        run: |
          rake gem:build
      - name: Install
        run: |
          rake gem:install
